import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import {User} from '../../types'


const Home: NextPage<{users:User[]}> = ({users}) => {
  // function NextPage({users:string})  {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        Home
        { JSON.stringify(users)}
        {
        users.map( us => {
        return (
          <div key={us.id}>
            <h2> {us.name}</h2>
            <h2> {us.lastname}</h2>
            <h2> {us.email}</h2>
          </div>

        )
      })
        }

      </div>


    </div>
  )
}


export default Home

export const getServerSideProps:GetServerSideProps = async (context) => {
//  const res = await fetch("https://www.freetogame.com/api/games")
const res = await fetch("http://ec2-3-92-193-151.compute-1.amazonaws.com/api/users")
 const  us_result = await res.json()
 console.log(us_result)

 return {
  props: {
    users : us_result
  }
 }
  
}
